/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CoachStaffRole;

import ui.StoreAdminRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CoachStaffOrganization;
import Business.Organization.CoachTrainerOrganization;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Cs2CtWorkRequest;
import Business.WorkQueue.Store2SupplierWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestProTrainOrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private Enterprise enterprise;
    private UserAccount userAccount;
    private CoachStaffOrganization organization;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestProTrainOrderJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount, Organization organization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.organization = (CoachStaffOrganization) organization;
        
        populateRoleComboBox(enterprise);
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        specialJComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestTestJButton.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 153, 0));
        requestTestJButton.setText("Confirm");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, -1, 50));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 153, 0));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Monaco", 1, 28)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 204, 204));
        enterpriseLabel.setText("Coach Staff");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 40));

        specialJComboBox.setBackground(new java.awt.Color(204, 204, 204));
        specialJComboBox.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        specialJComboBox.setForeground(new java.awt.Color(255, 153, 0));
        specialJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        specialJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specialJComboBoxActionPerformed(evt);
            }
        });
        add(specialJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 160, 40));

        workRequestJTable.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(255, 153, 0));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ChooseSpecial", "Processer", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 570, 180));

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshTestJButton.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(255, 153, 0));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 170, 40));

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Choose Special:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateRoleComboBox(Enterprise enterprise){
        specialJComboBox.removeAllItems();
        
        specialJComboBox.addItem("All");            
        specialJComboBox.addItem("Boxing");            
        specialJComboBox.addItem("Running");            
        specialJComboBox.addItem("Dumbbel");
        specialJComboBox.addItem("Barbell");
        specialJComboBox.addItem("Yoga");
        
    }
    
    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        Cs2CtWorkRequest request = new Cs2CtWorkRequest();
        String message = (String)specialJComboBox.getSelectedItem();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        // add workrequest in current useraccount and target organization
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        for(Organization og: enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(og instanceof CoachTrainerOrganization) {
                og.getWorkQueue().getWorkRequestList().add(request);
                break;
            }
        }
        JOptionPane.showMessageDialog(this,"Request sends successfully!");
        populateRequestTable();
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void specialJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specialJComboBoxActionPerformed
       
    }//GEN-LAST:event_specialJComboBoxActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed
    
    
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof Cs2CtWorkRequest) {
                Object[] row = new Object[3];
                row[0] = request.getMessage();
                row[1] = request.getReceiver();
                row[2] = request.getStatus();

                model.addRow(row);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JComboBox specialJComboBox;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
