/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.CafeAdminRole;


import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.CafeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.MenuItem;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageMenuItemsPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private CafeEnterprise enterprise; 

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageMenuItemsPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = (CafeEnterprise) enterprise; 
        if(this.enterprise.getMenuItems() == null){
            this.enterprise.setMenuItems(new ArrayList<MenuItem>());
        }
        populateTable();
    }
    
      private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblMenuItems.getModel();
        model.setRowCount(0);    
          for(MenuItem menuItem : enterprise.getMenuItems()){
               Object[] row = new Object[2]; 
            row[0] = menuItem; 
            row[1] = menuItem.getPrice(); 
            model.addRow(row);
          }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenuItems = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        lblCreateUser = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 0));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblMenuItems.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        tblMenuItems.setForeground(new java.awt.Color(255, 153, 0));
        tblMenuItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Menu Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblMenuItems);

        lblTitle.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 204, 255));
        lblTitle.setText("Manage Menu Items:");

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 153, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 204, 255));
        lblUserName.setText("Item Name:");

        lblPassword.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 204, 255));
        lblPassword.setText("Price:");

        btnAddItem.setBackground(new java.awt.Color(204, 204, 255));
        btnAddItem.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 153, 0));
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        lblCreateUser.setFont(new java.awt.Font("Monaco", 1, 16)); // NOI18N
        lblCreateUser.setForeground(new java.awt.Color(255, 153, 0));
        lblCreateUser.setText("Add Menu Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(140, 140, 140)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblCreateUser))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblUserName)
                                .addGap(18, 18, 18)
                                .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lblPassword)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAddItem)
                                    .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblTitle)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblCreateUser)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(btnAddItem)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(btnDelete))
                .addContainerGap(55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
       int row = tblMenuItems.getSelectedRow();
       if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       MenuItem menuItem = (MenuItem) tblMenuItems.getValueAt(row, 0);
       for (MenuItem item : enterprise.getMenuItems()){
           if(item.equals(menuItem)){
               enterprise.getMenuItems().remove(item);
               break;
           }
       }
       JOptionPane.showMessageDialog(this, "Selected menu item has been deleted.", "Information", JOptionPane.INFORMATION_MESSAGE);
       populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed
    private boolean isValidDouble(String s){
            boolean isValidDouble = false;
          try
          {
             Double.parseDouble(s);
             isValidDouble = true;
          }
          catch (NumberFormatException ex)
          {
             // s is not an integer
          }
          return isValidDouble;
        }
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
       String itemName = txtItemName.getText(); 
       String price = txtItemPrice.getText(); 
       ArrayList<MenuItem> menuItems = enterprise.getMenuItems(); 
        if (itemName.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the missing menu Item information.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!isValidDouble(price)){
             JOptionPane.showMessageDialog(this, "Please provide a valid number for the Item price.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        MenuItem menuItem = new MenuItem(enterprise , itemName); 
        menuItem.setMenuItemPrice(Double.valueOf(price));
        menuItems.add(menuItem); 
        populateTable();
    }//GEN-LAST:event_btnAddItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblMenuItems;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    // End of variables declaration//GEN-END:variables
}
