/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.FoodSupplierRole;


import ui.CafeAdminRole.*;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.CafeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.FoodItem;
import Business.Organization.FoodSupplierOrganization;
import Business.Organization.MenuItem;

import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageFoodItemsPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private Enterprise enterprise; 
    private FoodSupplierOrganization foodSupplier; 
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageFoodItemsPanel(JPanel userProcessContainer, FoodSupplierOrganization foodSupplier, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise; 
        this.foodSupplier = foodSupplier; 
        if(this.foodSupplier.getFoodItems() == null){
            this.foodSupplier.setFoodItems(new ArrayList<FoodItem>());
        }
        populateTable();
    }
    
      private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblMenuItems.getModel();
        model.setRowCount(0);    
          for(FoodItem foodItem : foodSupplier.getFoodItems()){
            Object[] row = new Object[2]; 
            row[0] = foodItem; 
            row[1] = foodItem.getPrice(); 
            model.addRow(row);
          }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenuItems = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        lblUserName = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        lblCreateUser = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 153, 0));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblMenuItems.setFont(new java.awt.Font("Monaco", 0, 14)); // NOI18N
        tblMenuItems.setForeground(new java.awt.Color(255, 153, 0));
        tblMenuItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Food Item", "Price"
            }
        ));
        jScrollPane1.setViewportView(tblMenuItems);

        lblTitle.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 204, 204));
        lblTitle.setText("Manage Food Items");

        btnDelete.setBackground(new java.awt.Color(204, 204, 255));
        btnDelete.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 153, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(0, 204, 204));
        lblUserName.setText("Food:");

        lblPassword.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 204, 204));
        lblPassword.setText("Price:");

        txtItemPrice.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        txtItemPrice.setForeground(new java.awt.Color(255, 153, 0));

        btnAddItem.setBackground(new java.awt.Color(204, 204, 255));
        btnAddItem.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 153, 0));
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        lblCreateUser.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        lblCreateUser.setForeground(new java.awt.Color(255, 153, 0));
        lblCreateUser.setText("Add Food Item");

        txtItemName.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        txtItemName.setForeground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(31, 31, 31)
                                .addComponent(btnDelete))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPassword)
                                            .addComponent(lblUserName))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAddItem)))
                                    .addComponent(lblCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(lblTitle)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCreateUser)
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserName)
                            .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassword)
                            .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
       int row = tblMenuItems.getSelectedRow();
       if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
       FoodItem foodItem = (FoodItem) tblMenuItems.getValueAt(row, 0);
       for (FoodItem item : foodSupplier.getFoodItems()){
           if(item.equals(foodItem)){
               foodSupplier.getFoodItems().remove(item);
               break;
           }
       }
       JOptionPane.showMessageDialog(this, "Selected food item has been deleted.", "Information", JOptionPane.INFORMATION_MESSAGE);
       populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed
    private boolean isValidDouble(String s){
            boolean isValidDouble = false;
          try
          {
             Double.parseDouble(s);
             isValidDouble = true;
          }
          catch (NumberFormatException ex)
          {
             // s is not an integer
          }
          return isValidDouble;
        }
    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
       String itemName = txtItemName.getText(); 
       String price = txtItemPrice.getText(); 
       ArrayList<FoodItem> foodItems = foodSupplier.getFoodItems(); 
        if (itemName.isEmpty() || price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please provide the missing food Item information.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!isValidDouble(price)){
             JOptionPane.showMessageDialog(this, "Please provide a valid number for the Item price.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FoodItem foodItem = new FoodItem(foodSupplier , itemName); 
        foodItem.setMenuItemPrice(Double.valueOf(price));
        foodItems.add(foodItem); 
        populateTable();
    }//GEN-LAST:event_btnAddItemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTable tblMenuItems;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    // End of variables declaration//GEN-END:variables
}
