/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.FoodSupplierRole;

import Business.Organization.FoodSupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.FoodOrder;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class ManageOrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private FoodSupplierOrganization foodSupplierOrganization;
    
    private UserAccount userAccount;
    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    public ManageOrderJPanel(JPanel userProcessContainer, UserAccount account, FoodSupplierOrganization foodSupplierOrganization) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.foodSupplierOrganization = foodSupplierOrganization; 
        this.userAccount = account;
        populateOrderHistoryTable();
        valueLabel.setText(foodSupplierOrganization.getName());
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnCancelOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrderHistory = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();
        btnConfirmOrder = new javax.swing.JButton();
        btnCompleteOrder = new javax.swing.JButton();
        cancelMessage = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        enterpriseLabel.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 204, 204));
        enterpriseLabel.setText("Manage Orders");

        valueLabel.setFont(new java.awt.Font("Monaco", 1, 22)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 153, 0));
        valueLabel.setText("<value>");

        btnCancelOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnCancelOrder.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(255, 153, 0));
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        TblOrderHistory.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        TblOrderHistory.setForeground(new java.awt.Color(0, 204, 204));
        TblOrderHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderItems", "Request Date", "Status", "Message"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TblOrderHistory);
        if (TblOrderHistory.getColumnModel().getColumnCount() > 0) {
            TblOrderHistory.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshTestJButton.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(255, 153, 0));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });

        btnConfirmOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnConfirmOrder.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnConfirmOrder.setForeground(new java.awt.Color(255, 153, 0));
        btnConfirmOrder.setText("Confirm Order");
        btnConfirmOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmOrderActionPerformed(evt);
            }
        });

        btnCompleteOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnCompleteOrder.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        btnCompleteOrder.setForeground(new java.awt.Color(255, 153, 0));
        btnCompleteOrder.setText("Complete Order");
        btnCompleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteOrderActionPerformed(evt);
            }
        });

        cancelMessage.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        cancelMessage.setForeground(new java.awt.Color(255, 153, 0));
        cancelMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMessageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valueLabel)
                                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(19, 19, 19)
                                        .addComponent(btnConfirmOrder)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnCompleteOrder)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refreshTestJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshTestJButton))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelOrder)
                    .addComponent(btnConfirmOrder)
                    .addComponent(btnCompleteOrder))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
       FoodOrder order = null;
      int row = TblOrderHistory.getSelectedRow();
       if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (FoodOrder)TblOrderHistory.getValueAt(row, 0); 
        order.setStatus("CANCELED");
        order.setMessage(cancelMessage.getText()); 
        JOptionPane.showMessageDialog(null, "Order has been canceled. ", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateOrderHistoryTable();
    }//GEN-LAST:event_btnCancelOrderActionPerformed
    void populateOrderHistoryTable(){
        DefaultTableModel model = (DefaultTableModel) TblOrderHistory.getModel();
        model.setRowCount(0);
        for(FoodOrder order : foodSupplierOrganization.getFoodOrders()){
                Object[] row = new Object[4];
                row[0] = order; 
                row[1] = order.getRequestDate().toString(); 
                row[2] = order.getStatus();
                row[3] = order.getMessage(); 
                model.addRow(row);
            
        }
    }
    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed
        populateOrderHistoryTable();
    }//GEN-LAST:event_refreshTestJButtonActionPerformed

    private void btnConfirmOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmOrderActionPerformed
       FoodOrder order = null;
       int row = TblOrderHistory.getSelectedRow();
       if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (FoodOrder)TblOrderHistory.getValueAt(row, 0); 
        order.setStatus("CONFIRMED");
        order.setMessage(cancelMessage.getText()); 
        JOptionPane.showMessageDialog(null, "Order has been confirmed. ", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateOrderHistoryTable();
    }//GEN-LAST:event_btnConfirmOrderActionPerformed

    private void btnCompleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteOrderActionPerformed
        // TODO add your handling code here:
       FoodOrder order = null;
       int row = TblOrderHistory.getSelectedRow();
       if(row < 0)
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        order = (FoodOrder)TblOrderHistory.getValueAt(row, 0); 
        order.setStatus("COMPLETED");
        order.setMessage(cancelMessage.getText()); 
        JOptionPane.showMessageDialog(null, "Order has been completed. ", "Information", JOptionPane.INFORMATION_MESSAGE);
        populateOrderHistoryTable();
    }//GEN-LAST:event_btnCompleteOrderActionPerformed

    private void cancelMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMessageActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblOrderHistory;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnCompleteOrder;
    private javax.swing.JButton btnConfirmOrder;
    private javax.swing.JTextField cancelMessage;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
