/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.StoreAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SupplierOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Store2SupplierWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raunak
 */
public class RequestSupplierOrderJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestSupplierOrderJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        
        
        
        populateRoleComboBox(enterprise);
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        backJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkJTable = new javax.swing.JTable();
        roleJComboBox = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        refreshTestJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        requestTestJButton.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 153, 0));
        requestTestJButton.setText("Place Order");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, 60));

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Order Detail:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, 20));

        messageJTextField.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        messageJTextField.setForeground(new java.awt.Color(255, 153, 0));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 450, -1));

        backJButton.setBackground(new java.awt.Color(204, 204, 255));
        backJButton.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 153, 0));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 100, 60));

        enterpriseLabel.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 204, 204));
        enterpriseLabel.setText("Store Admin:");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        networkJTable.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        networkJTable.setForeground(new java.awt.Color(255, 153, 0));
        networkJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "MaterialName"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(networkJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 270, 170));

        roleJComboBox.setBackground(new java.awt.Color(204, 204, 255));
        roleJComboBox.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        roleJComboBox.setForeground(new java.awt.Color(255, 153, 0));
        roleJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        roleJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleJComboBoxActionPerformed(evt);
            }
        });
        add(roleJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 30));

        workRequestJTable.setFont(new java.awt.Font("Monaco", 1, 14)); // NOI18N
        workRequestJTable.setForeground(new java.awt.Color(255, 153, 0));
        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "OrderDetail", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(workRequestJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 770, 180));

        refreshTestJButton.setBackground(new java.awt.Color(204, 204, 255));
        refreshTestJButton.setFont(new java.awt.Font("Monaco", 1, 20)); // NOI18N
        refreshTestJButton.setForeground(new java.awt.Color(255, 153, 0));
        refreshTestJButton.setText("Refresh");
        refreshTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshTestJButtonActionPerformed(evt);
            }
        });
        add(refreshTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 480, 140, 50));
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateRoleComboBox(Enterprise enterprise){
        roleJComboBox.removeAllItems();
        for(Organization og: enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(og instanceof SupplierOrganization) {
                for(UserAccount ua : og.getUserAccountDirectory().getUserAccountList()) {
                    roleJComboBox.addItem(ua);
                }
                break;
            }
        }
        
    }
    
    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        if(messageJTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Input");
            return;
        }
        String message = messageJTextField.getText();
        
        Store2SupplierWorkRequest request = new Store2SupplierWorkRequest(); // no abstract class
        request.setMessage(message);
        request.setSender(userAccount);
        request.setStatus("Sent");
        
        UserAccount ua = (UserAccount) roleJComboBox.getSelectedItem();
        request.setReceiver(ua);
        request.setSupplierUserName(ua.toString());

        // add workrequest in current useraccount and target organization
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        for(Organization og: enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(og instanceof SupplierOrganization) {
                og.getWorkQueue().getWorkRequestList().add(request);
                break;
            }
        }
        JOptionPane.showMessageDialog(this,"Order created!");
        populateRequestTable();
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void roleJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleJComboBoxActionPerformed
        // TODO add your handling code here:

        UserAccount ua = (UserAccount) roleJComboBox.getSelectedItem();
        if (ua != null){
            populateNetworkTable(ua);
        }
    }//GEN-LAST:event_roleJComboBoxActionPerformed

    private void refreshTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshTestJButtonActionPerformed

        populateRequestTable();

    }//GEN-LAST:event_refreshTestJButtonActionPerformed
    
    private void populateNetworkTable(UserAccount ua) {
        DefaultTableModel model = (DefaultTableModel) networkJTable.getModel();

        model.setRowCount(0);
        for (String s : ua.getMaterialList()) {
            Object[] row = new Object[1];
            row[0] = s;
            model.addRow(row);
        }
    }
    
    public void populateRequestTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof Store2SupplierWorkRequest) {
                Object[] row = new Object[4];
                row[0] = request.getMessage();
                row[1] = request.getReceiver();
                row[2] = request.getStatus();
                String result = ((Store2SupplierWorkRequest)request).getTestResult();
                row[3] = result == null ? "Waiting" : result;

                model.addRow(row);
            }
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTable networkJTable;
    private javax.swing.JButton refreshTestJButton;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JComboBox roleJComboBox;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
