

package ui.StoreAdminRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.StoreEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  raunak
 */
public class StoreAdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount userAccount;
    /** Creates new form AdminWorkAreaJPanel */
    public StoreAdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        valueLabel.setText(enterprise.getName());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageOrganizationJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        btnMakeManufOrder = new javax.swing.JButton();
        btnMakeSupplierOrder1 = new javax.swing.JButton();
        productJButton = new javax.swing.JButton();
        orderJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Store Admin Role Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, 50));

        userJButton.setBackground(new java.awt.Color(204, 204, 255));
        userJButton.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        userJButton.setForeground(new java.awt.Color(255, 153, 0));
        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 150, -1));

        manageEmployeeJButton.setBackground(new java.awt.Color(204, 204, 255));
        manageEmployeeJButton.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(255, 153, 0));
        manageEmployeeJButton.setText("Manage Employee & Working partners");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 430, -1));

        manageOrganizationJButton.setBackground(new java.awt.Color(204, 204, 255));
        manageOrganizationJButton.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        manageOrganizationJButton.setForeground(new java.awt.Color(255, 153, 0));
        manageOrganizationJButton.setText("Manage Organization");
        manageOrganizationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButtonActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 270, -1));

        enterpriseLabel.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 153, 0));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 180, 30));

        valueLabel.setFont(new java.awt.Font("Monaco", 1, 24)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 204, 204));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 130, -1));

        btnMakeManufOrder.setBackground(new java.awt.Color(204, 204, 255));
        btnMakeManufOrder.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        btnMakeManufOrder.setForeground(new java.awt.Color(255, 153, 0));
        btnMakeManufOrder.setText("Make Manufacturer order");
        btnMakeManufOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeManufOrderActionPerformed(evt);
            }
        });
        add(btnMakeManufOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 320, -1));

        btnMakeSupplierOrder1.setBackground(new java.awt.Color(204, 204, 255));
        btnMakeSupplierOrder1.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        btnMakeSupplierOrder1.setForeground(new java.awt.Color(255, 153, 0));
        btnMakeSupplierOrder1.setText("Make supplier order");
        btnMakeSupplierOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeSupplierOrder1ActionPerformed(evt);
            }
        });
        add(btnMakeSupplierOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 270, -1));

        productJButton.setBackground(new java.awt.Color(204, 204, 255));
        productJButton.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        productJButton.setForeground(new java.awt.Color(255, 153, 0));
        productJButton.setText("Manage Product");
        productJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productJButtonActionPerformed(evt);
            }
        });
        add(productJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 210, -1));

        orderJButton.setBackground(new java.awt.Color(204, 204, 255));
        orderJButton.setFont(new java.awt.Font("Monaco", 1, 18)); // NOI18N
        orderJButton.setForeground(new java.awt.Color(255, 153, 0));
        orderJButton.setText("Manage Order");
        orderJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderJButtonActionPerformed(evt);
            }
        });
        add(orderJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 160, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesss/store.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 320, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageEmployeeJPanel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageOrganizationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButtonActionPerformed

        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButtonActionPerformed

    private void btnMakeManufOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeManufOrderActionPerformed
        // TODO add your handling code here:
        RequestManufacturerOrderJPanel requestManufacturerOrderJPanel = new RequestManufacturerOrderJPanel(userProcessContainer, enterprise, userAccount);
        userProcessContainer.add("requestManufacturerOrderJPanel", requestManufacturerOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMakeManufOrderActionPerformed

    private void btnMakeSupplierOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeSupplierOrder1ActionPerformed
        // TODO add your handling code here:
        RequestSupplierOrderJPanel requestSupplierOrderJPanel = new RequestSupplierOrderJPanel(userProcessContainer, enterprise, userAccount);
        userProcessContainer.add("requestSupplierOrderJPanel", requestSupplierOrderJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMakeSupplierOrder1ActionPerformed

    private void productJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productJButtonActionPerformed
        // TODO add your handling code here:
        ManageProductsPanel manageProductJPanel = new ManageProductsPanel(userProcessContainer, enterprise);
        userProcessContainer.add("manageProductJPanel", manageProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_productJButtonActionPerformed

    private void orderJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderJButtonActionPerformed
        // TODO add your handling code here:
        ManageOrderJPanel manageProductJPanel = new ManageOrderJPanel(userProcessContainer, userAccount, (StoreEnterprise) enterprise);
        userProcessContainer.add("manageProductJPanel", manageProductJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_orderJButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeManufOrder;
    private javax.swing.JButton btnMakeSupplierOrder1;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton;
    private javax.swing.JButton orderJButton;
    private javax.swing.JButton productJButton;
    private javax.swing.JButton userJButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
    
}
